# -*- coding: utf-8 -*-
"""june16_ffn_signal_reconstruction (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tJ2qxpuGb4OQOkP78hU8p01yIeAY8HNB

# SciNoNet: Helmholtz-Potential PINN

Self-contained physics-informed network for guided-wave (Lamb) displacement
reconstruction on an aluminum plate. The network predicts four Helmholtz
potentials `(phi, psi_x, psi_y, psi_z)` from standardized coordinates
`(x, y, z, t)`; displacement `(u, v, w)` is obtained from the potentials by
autograd, and the potentials are constrained by two scalar wave equations
(P-speed for `phi`, S-speed for the three `psi`), the Coulomb gauge, and a rest
initial condition.

Input data is the CSV produced by the data-extraction notebook
(`data_extraction.ipynb`), columns `[x, y, z, t, u, v, w]` with `(x, y, z)` in
mm, `t` in s, `(u, v, w)` in mm.
"""

import os
import copy
import time
import math
import random
import warnings

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import matplotlib as mpl

warnings.filterwarnings("ignore")
torch.set_default_dtype(torch.float64)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Running on {DEVICE}")
if DEVICE.type == "cuda":
    print(f"GPU: {torch.cuda.get_device_name(0)}")

def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

SEED = 42
set_seed(SEED)

import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="matplotlib.font_manager")

import logging
logging.getLogger("matplotlib.font_manager").setLevel(logging.ERROR)

"""## Configuration

All hyperparameters live here (no magic numbers below). Wave speeds are the
handbook bulk values for structural aluminum, in mm/s.
"""

CSV_PATH = "dataset_4nbhd_50pts_3ply_fullsignal_6001steps.csv"

DT = 1e-8        # simulation timestep [s]
N_T = 6001       # timesteps per spatial point in the full signal

# Bulk wave speeds for 6061-T6 aluminum [mm/s]. Handbook ultrasonic values are
# c_p ~ 6.30 mm/us and c_s ~ 3.20 mm/us; only their ratio gamma = c_s / c_p
# enters the non-dimensional physics (the time scale tau = L_x / c_p absorbs
# the absolute P speed).

CP_MM_PER_S = 6.30e6   # longitudinal (P) wave speed [mm/s]
CS_MM_PER_S = 3.20e6   # shear (S) wave speed [mm/s]

# Fourier-feature dispersion bands (standardized cycles per unit are derived
# from these physical limits times the per-axis coordinate scale).
K_MAX_SPATIAL = 0.13   # cyc/mm, in-plane band (kappa <= 0.8 rad/mm)
SPATIAL_SCALE = 2.0    # tuning multiplier on the spatial band
F_MAX_HZ = 300e3       # max temporal frequency [Hz]
NUM_FREQ = 160         # number of Fourier bases L (embedding dim = 2L)

HIDDEN_SIZES = [256, 256, 256]
ACTIVATION = "tanh"
CONCAT_RAW = True

# Train/test construction is a two-stage split.
#   Stage 1 (spatial holdout): N_HELD_SPATIAL unique (x, y) points are removed
#     from training entirely. The model sees no timestep of these signals, so
#     their full-signal prediction is a pure spatial extrapolation. They are
#     drawn spread across neighborhoods (round-robin) rather than clustered.
#   Stage 2 (temporal holdout): on every remaining point, a random fraction
#     SUBSAMPLE_KEEP of timesteps is kept for training; the complement is the
#     temporal evaluation set for those seen points.
N_HELD_SPATIAL = 10    # unique (x, y) points excluded from training entirely
SUBSAMPLE_KEEP = 0.10  # fraction of timesteps kept per *trained* point

# Training
EPOCHS = 80
BATCH_SIZE = 16384
N_COLLOC = 2048        # collocation points per step (wave + gauge residual)
N_IC = 1024            # initial-condition points per step
LR = 2e-3
GRAD_CLIP = 1.0
DATA_ONLY_EPOCHS = 12  # data-only warmup before physics turns on
BALANCE_ALPHA = 0.3    # physics gradient as a fraction of the data gradient
BALANCE_EMA = 0.9
W_GAUGE = 1.0
W_IC = 1.0
SCHED_FACTOR = 0.5
SCHED_PATIENCE = 15
MIN_LR = 1e-5
EARLY_STOP_PATIENCE = EPOCHS
LOG_EVERY = 1

SURFACE_Z = 0.0        # z level used for reconstruction plots
FIELD_COLS = ["u", "v", "w"]

"""## Plot style (academic palette)"""

AC = {
    "blue": "#2563EB", "amber": "#D97706", "green": "#059669", "red": "#DC2626",
    "axis": "#212529", "grid": "#E9ECEF", "text": "#212529", "muted": "#212529",
    "ink": "#212529",
}

# Global typography. Large and dark, but not bold, per the requested style. Every
# size below is roughly 2-2.5x the previous values; per-plot titles add more on
# top. Weight stays "regular" so labels read dark without being heavy.
mpl.rcParams.update({
    "font.family": "sans-serif",
    "font.sans-serif": ["Inter", "Helvetica", "Arial", "DejaVu Sans"],
    "font.weight": "regular",
    "axes.titleweight": "regular",
    "axes.labelweight": "regular",
})


def apply_style() -> None:
    mpl.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": ["Inter", "Helvetica", "Arial", "DejaVu Sans"],
        # Only the outer frame: all four spines on, no interior grid.
        "axes.spines.top": True,
        "axes.spines.right": True,
        "axes.spines.left": True,
        "axes.spines.bottom": True,
        "axes.grid": False,
        "axes.edgecolor": AC["axis"],
        "axes.linewidth": 1.4,
        # Dark, regular-weight text, sized up substantially.
        "font.size": 20,
        "axes.titlesize": 26,
        "axes.labelsize": 22,
        "axes.titleweight": "regular",
        "axes.labelweight": "regular",
        "axes.labelcolor": AC["text"],
        "axes.titlecolor": AC["text"],
        "xtick.labelsize": 18,
        "ytick.labelsize": 18,
        "xtick.color": AC["text"],
        "ytick.color": AC["text"],
        "legend.fontsize": 18,
        "figure.titlesize": 30,
        "figure.dpi": 150,
        "savefig.dpi": 300,
        "savefig.bbox": "tight",
    })


def save_fig(fig, save_stem):
    if save_stem is None:
        return
    os.makedirs(os.path.dirname(save_stem) or ".", exist_ok=True)
    fig.savefig(f"{save_stem}.png", dpi=300, bbox_inches="tight", facecolor="white")
    fig.savefig(f"{save_stem}.svg", bbox_inches="tight", facecolor="white")
    print(f"saved: {save_stem}.png / .svg")


apply_style()

"""## Data

Load the full-signal CSV and attach a per-point integer timestep index `t_idx`
(robust to row order). Then standardize and build the temporal train/test
split.
"""

# Candidate names for the neighborhood id column, in priority order. The first
# one present in the CSV is used; matching is case-insensitive. If none match,
# NBHD_COL stays None and the whole sampled region is treated as one group.
_NBHD_CANDIDATES = ["nbhd", "neighborhood", "neighbourhood", "neighbor",
                    "neighbour", "nbr", "group", "region", "cluster", "patch",
                    "block", "zone"]

NBHD_COL = None  # resolved at load time; printed so it can be verified


def _detect_nbhd_col(columns) -> "str | None":
    """Return the neighborhood id column name, or None if absent.

    Coordinate and field columns are never treated as neighborhood ids even if
    a candidate name happens to collide.
    """
    reserved = {"x", "y", "z", "t", "u", "v", "w", "t_idx"}
    lower = {c.lower(): c for c in columns}
    for cand in _NBHD_CANDIDATES:
        if cand in lower and lower[cand].lower() not in reserved:
            return lower[cand]
    # Heuristic fallback: any column whose name contains "nbhd"/"neigh".
    for c in columns:
        cl = c.lower()
        if ("nbhd" in cl or "neigh" in cl) and cl not in reserved:
            return c
    return None


def load_full_signal(csv_path: str) -> pd.DataFrame:
    global NBHD_COL
    df = pd.read_csv(csv_path)
    NBHD_COL = _detect_nbhd_col(df.columns)
    df = df.sort_values(["x", "y", "z", "t"]).reset_index(drop=True)
    df["t_idx"] = np.round(df["t"].to_numpy() / DT - 1).astype(int)
    if NBHD_COL is None:
        # No id column: derive a single-group label so downstream code that
        # expects a neighborhood column still works.
        df["nbhd"] = 0
        NBHD_COL = "nbhd"
        print("neighborhood column: none found, using a single group")
    else:
        print(f"neighborhood column: '{NBHD_COL}' "
              f"({df[NBHD_COL].nunique()} unique groups)")
    return df

df = load_full_signal(CSV_PATH)
print("rows:", len(df), "| columns:", list(df.columns))
df.head()

"""### Standardization scalers

Each spatial axis is referred to its own length scale `L_x, L_y, L_z` (the
per-axis coordinate std), so the standardized coordinates run over O(1)
ranges. The time scale is the P-wave transit time `tau = L_x / c_p`, which
normalizes the `phi` wave equation. Two geometric aspect ratios survive,
`beta_y = L_x/L_y` and `beta_z = L_x/L_z`, together with the single material
speed ratio `gamma = c_s/c_p`. Field scale `s_f` is the common std of
`(u, v, w)`; the inverse map back to physical displacement is `u = s_f * u_hat`.
"""

class PotentialScalers:
    """Non-dimensionalization following the elastic-wave derivation.

    Each spatial axis is referred to its own physical length scale, so that the
    standardized coordinates run over O(1) ranges:

        x_hat = (x - mu_x) / L_x,   y_hat = (y - mu_y) / L_y,
        z_hat = (z - mu_z) / L_z,   t_hat = (t - mu_t) / tau.

    The time scale is fixed to the P-wave transit time across the x-extent,
    tau = L_x / c_p, which normalizes the phi wave equation. Two geometric
    aspect ratios then survive,

        beta_y = L_x / L_y,   beta_z = L_x / L_z,

    together with the single material speed ratio gamma = c_s / c_p (the only
    speed left after tau absorbs c_p). The fields are standardized by a single
    common scale s_f so the data loss compares O(1) quantities, and the inverse
    map back to physical displacement is u = s_f * u_hat.
    """

    def __init__(self, mu_x, mu_y, Lx, mu_y_, Ly, mu_z, Lz, mu_t, tau, s_f,
                 cp_mm_per_s, cs_mm_per_s):
        self.mu_x = mu_x; self.Lx = Lx
        self.mu_y = mu_y; self.Ly = Ly
        self.mu_z = mu_z; self.Lz = Lz
        self.mu_t = mu_t; self.tau = tau
        self.s_f = s_f
        self.cp = cp_mm_per_s; self.cs = cs_mm_per_s

    @classmethod
    def fit(cls, frame: "pd.DataFrame", cp_mm_per_s: float,
            cs_mm_per_s: float) -> "PotentialScalers":
        Lx = float(frame["x"].std() + 1e-12)
        Ly = float(frame["y"].std() + 1e-12)
        Lz = float(frame["z"].std() + 1e-12)
        # Guard a degenerate through-thickness spread (e.g. very few z layers):
        # fall back to the in-plane scale so beta_z stays finite and O(1).
        if Lz < 1e-9:
            Lz = Lx
        tau = Lx / cp_mm_per_s
        uvw = np.concatenate([frame["u"].to_numpy(), frame["v"].to_numpy(),
                              frame["w"].to_numpy()])
        s_f = float(uvw.std() + 1e-30)
        return cls(
            mu_x=float(frame["x"].mean()), Lx=Lx,
            mu_y=float(frame["y"].mean()), mu_y_=None, Ly=Ly,
            mu_z=float(frame["z"].mean()), Lz=Lz,
            mu_t=float(frame["t"].mean()), tau=tau,
            s_f=s_f, cp_mm_per_s=cp_mm_per_s, cs_mm_per_s=cs_mm_per_s,
        )

    @property
    def beta_y(self) -> float:
        """Aspect ratio L_x / L_y multiplying the y second derivative."""
        return self.Lx / self.Ly

    @property
    def beta_z(self) -> float:
        """Aspect ratio L_x / L_z multiplying the z second derivative."""
        return self.Lx / self.Lz

    @property
    def gamma(self) -> float:
        """Material speed ratio c_s / c_p (the surviving speed parameter)."""
        return self.cs / self.cp

    def encode(self, x, y, z, t) -> np.ndarray:
        return np.stack([(x - self.mu_x) / self.Lx,
                         (y - self.mu_y) / self.Ly,
                         (z - self.mu_z) / self.Lz,
                         (t - self.mu_t) / self.tau], axis=1)

    def decode_fields(self, uvw_hat: np.ndarray) -> np.ndarray:
        """Map standardized displacement back to physical units (mm)."""
        return uvw_hat * self.s_f

"""### Train/test split (spatial then temporal)

Stage 1 removes `N_HELD_SPATIAL` unique points from training entirely (spatial
holdout, spread across neighborhoods). Stage 2 keeps a random fraction
`SUBSAMPLE_KEEP` of timesteps on every remaining point. Scalers are fitted on
training rows only.
"""

def _choose_spatial_holdout(xy_points, nbhd_of_point, n_held, seed):
    """Pick n_held unique (x, y) indices to exclude, spread across groups.

    Points are drawn round-robin over neighborhoods so the spatial holdout is
    not clustered in a single region. Within each group the choice is random
    under the given seed. Returns a sorted list of indices into xy_points.
    """
    rng = np.random.RandomState(seed)
    groups = {}
    for idx, g in enumerate(nbhd_of_point):
        groups.setdefault(g, []).append(idx)
    for g in groups:
        rng.shuffle(groups[g])
    order = sorted(groups.keys(), key=lambda g: str(g))
    held, gi = [], 0
    n_held = min(n_held, len(xy_points))
    while len(held) < n_held:
        g = order[gi % len(order)]
        if groups[g]:
            held.append(groups[g].pop())
        gi += 1
        if gi > len(order) * (len(xy_points) + 1):  # safety: pool exhausted
            break
    return sorted(held)


def build_dataset(df: pd.DataFrame, subsample_keep: float, n_held_spatial: int,
                  seed: int):
    """Two-stage split: spatial holdout, then temporal subsample on the rest.

    is_train     True for the kept training rows (trained points, kept timesteps)
    held_spatial True for every row of a spatially excluded point (never trained)
    """
    df = df.copy()

    # --- unique spatial points and their neighborhood ids -------------------
    xy_df = df[["x", "y", NBHD_COL]].drop_duplicates(subset=["x", "y"])
    xy_df = xy_df.sort_values(["x", "y"]).reset_index(drop=True)
    xy_points = xy_df[["x", "y"]].to_numpy()
    nbhd_of_point = xy_df[NBHD_COL].to_numpy()
    z_values = np.sort(df["z"].unique())

    # --- stage 1: spatial holdout (exclude whole signals) -------------------
    held_idx = _choose_spatial_holdout(xy_points, nbhd_of_point,
                                       n_held_spatial, seed)
    held_xy = set(map(tuple, xy_points[held_idx]))
    point_key = list(zip(df["x"].to_numpy(), df["y"].to_numpy()))
    held_spatial = np.array([k in held_xy for k in point_key])
    df["held_spatial"] = held_spatial

    # --- stage 2: temporal subsample on the trained points only -------------
    rng = np.random.RandomState(seed + 1)
    keep = (rng.rand(len(df)) < subsample_keep) & (~held_spatial)
    df["is_train"] = keep

    tr = df[keep]
    # Validation = temporal holdout on the trained points (seen spatial points,
    # unseen timesteps). The spatially held points are evaluated separately.
    te = df[(~keep) & (~held_spatial)]
    sc = PotentialScalers.fit(tr, CP_MM_PER_S, CS_MM_PER_S)

    def to_xy(frame):
        X = sc.encode(frame["x"].to_numpy(), frame["y"].to_numpy(),
                      frame["z"].to_numpy(), frame["t"].to_numpy())
        Y = frame[FIELD_COLS].to_numpy() / sc.s_f
        return (torch.tensor(X, dtype=torch.float64),
                torch.tensor(Y, dtype=torch.float64))

    Xtr, Ytr = to_xy(tr)
    Xte, Yte = to_xy(te)

    allc = sc.encode(df["x"].to_numpy(), df["y"].to_numpy(),
                     df["z"].to_numpy(), df["t"].to_numpy())
    colloc_lo = torch.tensor(allc.min(0), dtype=torch.float64)
    colloc_hi = torch.tensor(allc.max(0), dtype=torch.float64)
    t0_std = float((0.0 - sc.mu_t) / sc.tau)

    return {
        "Xtr": Xtr, "Ytr": Ytr, "Xte": Xte, "Yte": Yte, "scalers": sc,
        "xy_points": xy_points, "nbhd_of_point": nbhd_of_point,
        "held_spatial_idx": held_idx, "z_values": z_values, "df": df,
        "colloc_lo": colloc_lo, "colloc_hi": colloc_hi, "t0_std": t0_std,
    }

data = build_dataset(df, SUBSAMPLE_KEEP, N_HELD_SPATIAL, SEED)
print(f"beta_y={data['scalers'].beta_y:.3f} | beta_z={data['scalers'].beta_z:.3f} "
      f"| gamma={data['scalers'].gamma:.3f} | train_rows={len(data['Xtr'])} "
      f"| test_rows={len(data['Xte'])} | xy_points={len(data['xy_points'])} "
      f"| spatial_holdout={len(data['held_spatial_idx'])}")

sc = data["scalers"]

print("Characteristic variables (fitted on training rows)")
print(f"  mu_x   = {sc.mu_x: .6e} mm     (mean x)")
print(f"  mu_y   = {sc.mu_y: .6e} mm     (mean y)")
print(f"  mu_z   = {sc.mu_z: .6e} mm     (mean z)")
print(f"  mu_t   = {sc.mu_t: .6e} s      (mean t)")
print(f"  Lx     = {sc.Lx: .6e} mm     (x length scale = std of x)")
print(f"  Ly     = {sc.Ly: .6e} mm     (y length scale = std of y)")
print(f"  Lz     = {sc.Lz: .6e} mm     (z length scale = std of z)")
print(f"  tau    = {sc.tau: .6e} s      (time scale = Lx / c_p)")
print(f"  s_f    = {sc.s_f: .6e} mm     (field scale = std of u,v,w)")
print(f"  beta_y = {sc.beta_y: .6f}          (Lx / Ly, multiplies y_hat second deriv)")
print(f"  beta_z = {sc.beta_z: .6f}          (Lx / Lz, multiplies z_hat second deriv)")
print(f"  gamma  = {sc.gamma: .6f}          (c_s / c_p, surviving speed ratio)")

"""## Neighborhood layout and the spatial holdout

Three panels. Left, every unique sampled point on the 300 x 200 mm plate,
colored by neighborhood, with the spatially held-out points (excluded from
training entirely) ringed in red. Middle, a per-neighborhood summary table
counting total, trained, and held-out points. Right, a zoom on one
neighborhood so the single held-out spatial point sits among its trained
neighbors on the sampling grid.

## Non-dimensionalization diagnostics

How far each variable's magnitude range moves when going from physical to standardized units. Physical columns span many orders (mm, s, nm-scale displacement); standardized columns should collapse to O(1).
"""

def nondim_diagnostics(df: "pd.DataFrame", sc: "PotentialScalers") -> "pd.DataFrame":
    """Tabulate the physical vs normalized range of every variable.

    Non-dimensionalization pulls coordinates and fields that span many orders
    of magnitude in physical units (mm, s, nm-scale displacement) onto a
    comparable O(1) range. The table below reports, for each variable, the
    physical min/max and the standardized min/max so the collapse is explicit
    (for example u in mm spans roughly 1e-5..1e-10 physically and about
    1e-1..1e-3 after normalization).
    """
    Xc = sc.encode(df["x"].to_numpy(), df["y"].to_numpy(),
                   df["z"].to_numpy(), df["t"].to_numpy())
    fields_hat = df[FIELD_COLS].to_numpy() / sc.s_f

    phys_map = {"x": df["x"].to_numpy(), "y": df["y"].to_numpy(),
                "z": df["z"].to_numpy(), "t": df["t"].to_numpy(),
                "u": df["u"].to_numpy(), "v": df["v"].to_numpy(),
                "w": df["w"].to_numpy()}
    hat_map = {"x": Xc[:, 0], "y": Xc[:, 1], "z": Xc[:, 2], "t": Xc[:, 3],
               "u": fields_hat[:, 0], "v": fields_hat[:, 1], "w": fields_hat[:, 2]}
    units = {"x": "mm", "y": "mm", "z": "mm", "t": "s",
             "u": "mm", "v": "mm", "w": "mm"}

    def abs_range(a):
        a = np.abs(np.asarray(a, dtype=float))
        a = a[np.isfinite(a) & (a > 0)]
        if a.size == 0:
            return 0.0, 0.0
        # Robust lower bound: 1st percentile of nonzero magnitudes, so the
        # pre-arrival rest values (effectively zero) do not dominate the "min".
        return np.percentile(a, 1.0), a.max()

    rows = []
    for name in ["x", "y", "z", "t", "u", "v", "w"]:
        plo, phi = abs_range(phys_map[name])
        hlo, hhi = abs_range(hat_map[name])
        rows.append({
            "variable": name,
            "physical_range": f"{plo:.2e} .. {phi:.2e} {units[name]}",
            "normalized_range": f"{hlo:.2e} .. {hhi:.2e}",
        })
    out = pd.DataFrame(rows).set_index("variable")

    print("Physical vs normalized range per variable")
    print(f"  scales: Lx={sc.Lx:.3e} mm  Ly={sc.Ly:.3e} mm  Lz={sc.Lz:.3e} mm  "
          f"tau={sc.tau:.3e} s  s_f={sc.s_f:.3e} mm")
    print(f"  params: beta_y={sc.beta_y:.3f}  beta_z={sc.beta_z:.3f}  "
          f"gamma={sc.gamma:.4f}\n")
    print(out.to_string())
    return out


diag = nondim_diagnostics(data["df"], data["scalers"])
diag

"""## Fourier-feature embedding

Dispersion-informed features: `B` is learnable but clamped each step to
per-dimension frequency bands derived from the Lamb-wave dispersion curve, and
the amplitude `A` sits outside the sinusoids. Bands are expressed directly in
standardized cycles-per-unit (a physical frequency `f` maps to `f * std`).
"""

class SpecializedFourierFeatures(nn.Module):
    def __init__(self, lo, hi, num_frequencies, seed=0):
        super().__init__()
        self.in_features = lo.numel()
        self.num_frequencies = num_frequencies
        lo = lo.to(torch.float64).unsqueeze(1)
        hi = hi.to(torch.float64).unsqueeze(1)

        gen = torch.Generator().manual_seed(seed)
        u = torch.rand(self.in_features, num_frequencies, generator=gen, dtype=torch.float64)
        self.B = nn.Parameter(lo + u * (hi - lo))
        self.A = nn.Parameter(torch.ones(num_frequencies, dtype=torch.float64))
        self.register_buffer("B_min", lo)
        self.register_buffer("B_max", hi)

    @property
    def out_features(self) -> int:
        return 2 * self.num_frequencies

    def clamp_B(self) -> None:
        with torch.no_grad():
            self.B.clamp_(self.B_min, self.B_max)

    def forward(self, x):
        proj = 2.0 * np.pi * (x @ self.B.to(x))
        amp = self.A.to(x)
        return torch.cat([amp * torch.sin(proj), amp * torch.cos(proj)], dim=-1)


def make_features(sc, seed):
    # Each spatial band is the physical wavenumber limit times that axis's own
    # length scale, since x_hat = (x - mu) / L_axis. The temporal band uses tau.
    ks = K_MAX_SPATIAL * SPATIAL_SCALE
    lo = torch.tensor([-ks * sc.Lx, -ks * sc.Ly, -ks * sc.Lz, 0.0], dtype=torch.float64)
    hi = torch.tensor([ks * sc.Lx, ks * sc.Ly, ks * sc.Lz, F_MAX_HZ * sc.tau], dtype=torch.float64)
    return SpecializedFourierFeatures(lo, hi, NUM_FREQ, seed=seed)

"""## Model

Fourier-feature MLP mapping `(x, y, z, t)` to the four potentials. The two
standardized wave speeds are stored as log-parameters but held fixed so that
`cp / cs` stays at its physical value.
"""

_ACTIVATIONS = {"gelu": nn.GELU, "tanh": nn.Tanh, "silu": nn.SiLU}


class PotentialNet(nn.Module):
    """Fourier-feature MLP mapping standardized (x, y, z, t) to four potentials.

    In the derivation's non-dimensional form the phi wave equation has unit
    leading coefficient, and the three psi equations carry gamma^2 = (c_s/c_p)^2
    on their Laplacian. Only gamma is therefore a physical parameter; it is held
    fixed at its handbook value so the P/S speed ratio is exact.
    """

    def __init__(self, features, hidden_sizes, gamma_init,
                 activation="tanh", concat_raw=True):
        super().__init__()
        self.features = features
        self.concat_raw = concat_raw
        act = _ACTIVATIONS[activation]
        in_dim = features.out_features + (features.in_features if concat_raw else 0)
        layers, prev = [], in_dim
        for width in hidden_sizes:
            layers += [nn.Linear(prev, width), act()]
            prev = width
        self.backbone = nn.Sequential(*layers)
        self.head = nn.Linear(prev, 4)   # phi, psi_x, psi_y, psi_z
        self.log_gamma = nn.Parameter(torch.tensor(float(np.log(gamma_init)),
                                                    dtype=torch.float64))

    @property
    def gamma(self):
        return torch.exp(self.log_gamma)

    def forward(self, x):
        e = self.features(x)
        if self.concat_raw:
            e = torch.cat([e, x], dim=-1)
        return self.head(self.backbone(e))


def make_net(sc, seed):
    net = PotentialNet(make_features(sc, seed), HIDDEN_SIZES,
                       gamma_init=sc.gamma,
                       activation=ACTIVATION, concat_raw=CONCAT_RAW)
    net.log_gamma.requires_grad_(False)   # fixed handbook speed ratio
    return net

"""## Physics

Displacement comes from the Helmholtz combination of potential first
derivatives, with cross-axis curl terms weighted by the aspect ratios
`beta_y, beta_z`. The wave residual follows the non-dimensional derivation
`coeff^2 (q_xx + beta_y^2 q_yy + beta_z^2 q_zz) - q_tt`, where `coeff = 1`
for `phi` (its equation fixes `tau = L_x/c_p`) and `coeff = gamma` for the
three `psi`. The Coulomb gauge enforces `div(psi) = 0`; the rest initial
condition forces the potentials and their time-derivatives to vanish at
`t = 0`. The network operates entirely on standardized quantities; physical
units are restored only at reconstruction by multiplying by `s_f`.
"""

def _grad(out, x):
    return torch.autograd.grad(out, x, grad_outputs=torch.ones_like(out),
                               create_graph=True)[0]


def displacement(model, x, beta_y, beta_z):
    """Helmholtz displacement u = grad(phi) + curl(psi) in standardized form.

    Physical derivatives map to standardized ones by d/dx = (1/Lx) d/dx_hat,
    etc. Writing every term over the common factor 1/Lx (so the leading grad
    phi terms have unit coefficient) the cross-axis curl terms pick up the
    aspect ratios beta_y = Lx/Ly and beta_z = Lx/Lz:

        u_hat = phi_x + beta_y psi_z,y - beta_z psi_y,z
        v_hat = beta_y phi_y + beta_z psi_x,z - psi_z,x
        w_hat = beta_z phi_z + psi_y,x - beta_y psi_x,y

    The overall constant scale s_f Lx is absorbed into s_f at decode time.
    """
    p = model(x)
    gphi = _grad(p[:, 0], x); gpx = _grad(p[:, 1], x)
    gpy = _grad(p[:, 2], x);  gpz = _grad(p[:, 3], x)
    u = gphi[:, 0] + beta_y * gpz[:, 1] - beta_z * gpy[:, 2]
    v = beta_y * gphi[:, 1] + beta_z * gpx[:, 2] - gpz[:, 0]
    w = beta_z * gphi[:, 2] + gpy[:, 0] - beta_y * gpx[:, 1]
    return torch.stack([u, v, w], dim=1)


def _wave_residual(q, x, coeff2, beta_y, beta_z):
    """Derivation residual: coeff2 (q_xx + beta_y^2 q_yy + beta_z^2 q_zz) - q_tt.

    coeff2 is 1 for phi (its equation set tau = Lx/c_p) and gamma^2 for the
    three psi components. A solution of the wave equation makes this vanish.
    """
    g = _grad(q, x)
    q_xx = _grad(g[:, 0], x)[:, 0]
    q_yy = _grad(g[:, 1], x)[:, 1]
    q_zz = _grad(g[:, 2], x)[:, 2]
    q_tt = _grad(g[:, 3], x)[:, 3]
    laplacian = q_xx + beta_y ** 2 * q_yy + beta_z ** 2 * q_zz
    return coeff2 * laplacian - q_tt


def physics_residuals(model, x, beta_y, beta_z):
    p = model(x)
    gamma2 = model.gamma ** 2
    one = torch.ones_like(gamma2)
    r_phi = _wave_residual(p[:, 0], x, one, beta_y, beta_z)
    r_px = _wave_residual(p[:, 1], x, gamma2, beta_y, beta_z)
    r_py = _wave_residual(p[:, 2], x, gamma2, beta_y, beta_z)
    r_pz = _wave_residual(p[:, 3], x, gamma2, beta_y, beta_z)
    # Coulomb gauge div(psi) = 0 in standardized variables, same aspect-ratio
    # weighting as the displacement curl terms.
    gauge = (_grad(p[:, 1], x)[:, 0] + beta_y * _grad(p[:, 2], x)[:, 1]
             + beta_z * _grad(p[:, 3], x)[:, 2])
    return torch.stack([r_phi, r_px, r_py, r_pz], dim=1), gauge


def ic_residual(model, x):
    p = model(x)
    p_t = torch.stack([_grad(p[:, k], x)[:, 3] for k in range(4)], dim=1)
    return torch.cat([p, p_t], dim=1)

"""## Dirichlet boundary condition

Optional fixed-value (Dirichlet) constraint on chosen plate edges. Set the edges, components, and pinned physical value in the config block. A value of 0 clamps the edge; the loss compares in standardized space.
"""

# ---------------------------------------------------------------------------
# Dirichlet boundary condition
# ---------------------------------------------------------------------------
# The manuscript models a finite plate; you can optionally pin the displacement
# on chosen physical edges to a fixed value. Set BDRY_ENABLE = True and fill in
# the edges and value below. Edges are named by the axis and side in physical
# coordinates: "x_min", "x_max", "y_min", "y_max", "z_min", "z_max".
#
#   BDRY_VALUE is the PHYSICAL displacement (mm) the edge is pinned to, applied
#   to whichever components BDRY_COMPONENTS lists. It is divided by s_f inside
#   the loss so the comparison happens in standardized space. A pinned value of
#   0.0 is a clamped (fixed, non-moving) edge.

BDRY_ENABLE = True
BDRY_EDGES = ["x_min", "x_max", "y_min", "y_max"]  # perimeter of the plate
BDRY_COMPONENTS = ["u", "v", "w"]                  # which displacement comps to pin
BDRY_VALUE = 0.0                                   # physical displacement [mm]
W_BDRY = 1.0                                       # boundary sub-weight
N_BDRY = 1024                                      # boundary points per step


_EDGE_AXIS = {"x_min": (0, "lo"), "x_max": (0, "hi"),
              "y_min": (1, "lo"), "y_max": (1, "hi"),
              "z_min": (2, "lo"), "z_max": (2, "hi")}
_COMP_IDX = {"u": 0, "v": 1, "w": 2}


def sample_boundary(data, n, device, dtype, edges=BDRY_EDGES):
    """Sample standardized collocation points lying on the chosen domain edges.

    For each requested edge the corresponding standardized coordinate is fixed
    to the domain min or max while the others are sampled uniformly. Points are
    split evenly across the listed edges.
    """
    lo, hi = data["colloc_lo"], data["colloc_hi"]
    lo = lo.to(device, dtype); hi = hi.to(device, dtype)
    if not edges:
        return torch.empty(0, 4, device=device, dtype=dtype, requires_grad=True)
    per = max(1, n // len(edges))
    chunks = []
    for edge in edges:
        axis, side = _EDGE_AXIS[edge]
        u = torch.rand(per, 4, device=device, dtype=dtype)
        x = lo + u * (hi - lo)
        x[:, axis] = lo[axis] if side == "lo" else hi[axis]
        chunks.append(x)
    xb = torch.cat(chunks, dim=0)
    return xb.requires_grad_(True)


def boundary_residual(model, x, sc, components=BDRY_COMPONENTS, value=BDRY_VALUE):
    """Dirichlet residual: predicted standardized displacement minus pinned value.

    The physical pinned value is converted to standardized units by dividing by
    the field scale s_f, matching the space the network predicts in.
    """
    if x.shape[0] == 0:
        return torch.zeros(0, len(components), device=x.device, dtype=x.dtype)
    disp = displacement(model, x, sc.beta_y, sc.beta_z)
    idx = [_COMP_IDX[c] for c in components]
    target_hat = value / sc.s_f
    return disp[:, idx] - target_hat

def sample_colloc(lo, hi, n, device, dtype):
    u = torch.rand(n, lo.numel(), device=device, dtype=dtype)
    return (lo.to(device, dtype) + u * (hi - lo).to(device, dtype)).requires_grad_(True)


def sample_ic(data, n, device, dtype):
    lo, hi = data["colloc_lo"], data["colloc_hi"]
    u = torch.rand(n, 4, device=device, dtype=dtype)
    x = lo.to(device, dtype) + u * (hi - lo).to(device, dtype)
    x[:, 3] = data["t0_std"]
    return x.requires_grad_(True)

"""## Training

Data loss (through the Helmholtz displacement) plus wave, gauge, and IC
residuals. The physics weight is set each epoch so the physics gradient is a
fixed fraction `alpha` of the data gradient, after a short data-only warmup. The
best model is the one with lowest validation data loss.
"""

def train(model, data, device, verbose=True):
    from torch.utils.data import DataLoader, TensorDataset

    dtype = next(model.parameters()).dtype
    model = model.to(device)
    sc = data["scalers"]
    beta_y, beta_z = sc.beta_y, sc.beta_z
    loader = DataLoader(TensorDataset(data["Xtr"], data["Ytr"]),
                        batch_size=BATCH_SIZE, shuffle=True)

    n_val = min(len(data["Xte"]), 16384)
    vperm = torch.randperm(len(data["Xte"]))[:n_val]
    Xte = data["Xte"][vperm].to(device, dtype)
    Yte = data["Yte"][vperm].to(device, dtype)

    opt = torch.optim.Adam(model.parameters(), lr=LR)
    sch = torch.optim.lr_scheduler.ReduceLROnPlateau(
        opt, mode="min", factor=SCHED_FACTOR, patience=SCHED_PATIENCE, min_lr=MIN_LR)
    mse = nn.MSELoss()
    params = [p for p in model.parameters() if p.requires_grad]

    def gnorm(loss):
        g = torch.autograd.grad(loss, params, retain_graph=True, allow_unused=True)
        return torch.sqrt(sum((gi.detach() ** 2).sum() for gi in g if gi is not None))

    # Fixed monitoring sets so physics curves are continuous from epoch 1.
    n_mon = min(N_COLLOC, 1024)
    mon_c = sample_colloc(data["colloc_lo"], data["colloc_hi"], n_mon, device, dtype)
    mon_i = sample_ic(data, min(N_IC, 512), device, dtype)
    val_c = sample_colloc(data["colloc_lo"], data["colloc_hi"], n_mon, device, dtype)
    val_i = sample_ic(data, min(N_IC, 512), device, dtype)
    mon_b = sample_boundary(data, min(N_BDRY, 512), device, dtype) if BDRY_ENABLE else None
    val_b = sample_boundary(data, min(N_BDRY, 512), device, dtype) if BDRY_ENABLE else None

    def phys_terms(xc, xi, xb):
        wave, gauge = physics_residuals(model, xc, beta_y, beta_z)
        w_l = mse(wave, torch.zeros_like(wave)).item()
        g_l = mse(gauge, torch.zeros_like(gauge)).item()
        i_l = mse(ic_residual(model, xi),
                  torch.zeros(xi.shape[0], 8, device=device, dtype=dtype)).item()
        if BDRY_ENABLE and xb is not None and xb.shape[0] > 0:
            br = boundary_residual(model, xb, sc)
            b_l = mse(br, torch.zeros_like(br)).item()
        else:
            b_l = 0.0
        return w_l, g_l, i_l, b_l

    keys = ["train_data", "train_wave", "train_gauge", "train_ic", "train_bdry",
            "train_total", "val_data", "val_wave", "val_gauge", "val_ic",
            "val_bdry", "val_total", "phys_w", "gamma"]
    hist = {k: [] for k in keys}
    best = float("inf"); best_state = copy.deepcopy(model.state_dict()); bad = 0
    phys_w = 0.0
    start = time.time()
    if verbose:
        print(f"[train] device={device} beta_y={beta_y:.3f} beta_z={beta_z:.3f} "
              f"gamma={sc.gamma:.3f} bdry={'on' if BDRY_ENABLE else 'off'} "
              f"params={sum(p.numel() for p in model.parameters()):,}")

    for ep in range(1, EPOCHS + 1):
        physics_on = ep > DATA_ONLY_EPOCHS
        model.train()
        dsum = wsum = gsum = isum = bsum = 0.0; nb = 0
        for xb_data, yb in loader:
            xb_data = xb_data.to(device, dtype).requires_grad_(True)
            yb = yb.to(device, dtype)
            opt.zero_grad()
            data_loss = mse(displacement(model, xb_data, beta_y, beta_z), yb)
            if physics_on:
                xc = sample_colloc(data["colloc_lo"], data["colloc_hi"], N_COLLOC, device, dtype)
                wave, gauge = physics_residuals(model, xc, beta_y, beta_z)
                wave_loss = mse(wave, torch.zeros_like(wave))
                gauge_loss = mse(gauge, torch.zeros_like(gauge))
                xi = sample_ic(data, N_IC, device, dtype)
                ic_loss = mse(ic_residual(model, xi),
                              torch.zeros(N_IC, 8, device=device, dtype=dtype))
                if BDRY_ENABLE:
                    xbd = sample_boundary(data, N_BDRY, device, dtype)
                    br = boundary_residual(model, xbd, sc)
                    bdry_loss = mse(br, torch.zeros_like(br))
                else:
                    bdry_loss = torch.zeros((), device=device, dtype=dtype)
                phys = (wave_loss + W_GAUGE * gauge_loss + W_IC * ic_loss
                        + W_BDRY * bdry_loss)
                if nb == 0:
                    gd, gp = gnorm(data_loss), gnorm(phys)
                    tgt = BALANCE_ALPHA * float(gd / (gp + 1e-12))
                    phys_w = (BALANCE_EMA * phys_w + (1 - BALANCE_EMA) * tgt) if phys_w > 0 else tgt
                loss = data_loss + phys_w * phys
            else:
                wave_loss = gauge_loss = ic_loss = bdry_loss = torch.zeros((), device=device, dtype=dtype)
                loss = data_loss
            loss.backward()
            if GRAD_CLIP:
                nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP)
            opt.step()
            if hasattr(model.features, "clamp_B"):
                model.features.clamp_B()
            dsum += data_loss.item(); wsum += float(wave_loss.item())
            gsum += float(gauge_loss.item()); isum += float(ic_loss.item())
            bsum += float(bdry_loss.item()); nb += 1

        model.eval()
        Xv = Xte.clone().requires_grad_(True)
        val_data = mse(displacement(model, Xv, beta_y, beta_z), Yte).item()
        sch.step(val_data)
        tw, tg, ti, tb = phys_terms(mon_c, mon_i, mon_b)
        vw, vg, vi, vb = phys_terms(val_c, val_i, val_b)
        tphys = tw + W_GAUGE * tg + W_IC * ti + W_BDRY * tb
        vphys = vw + W_GAUGE * vg + W_IC * vi + W_BDRY * vb
        for k, val in [("train_data", dsum / nb), ("train_wave", tw), ("train_gauge", tg),
                       ("train_ic", ti), ("train_bdry", tb),
                       ("train_total", dsum / nb + phys_w * tphys),
                       ("val_data", val_data), ("val_wave", vw), ("val_gauge", vg),
                       ("val_ic", vi), ("val_bdry", vb),
                       ("val_total", val_data + phys_w * vphys),
                       ("phys_w", phys_w), ("gamma", model.gamma.item())]:
            hist[k].append(val)

        if val_data < best - 1e-12:
            best = val_data; best_state = copy.deepcopy(model.state_dict()); bad = 0
        else:
            bad += 1
        if verbose and (ep % LOG_EVERY == 0 or ep == 1):
            print(f"ep {ep:04d} | data {dsum/nb:.2e} | wave {wsum/nb:.2e} "
                  f"| gauge {gsum/nb:.2e} | ic {isum/nb:.2e} | bdry {bsum/nb:.2e} "
                  f"| val {val_data:.2e} | best {best:.2e} | w {phys_w:.3f}")
        if bad >= EARLY_STOP_PATIENCE:
            if verbose:
                print(f"early stop {ep}")
            break

    model.load_state_dict(best_state)
    if verbose:
        print(f"[train] done {(time.time()-start)/60:.2f} min | best val {best:.2e}")
    return hist, {"val_data_mse": best}

# training cell

set_seed(SEED)
model = make_net(data["scalers"], SEED)
history, metrics = train(model, data, DEVICE)
print(metrics)

"""## Loss curves"""

def plot_loss_curves(hist, data_only_epochs, save_stem=None):
    """One separate figure per loss component, saved individually."""
    comps = [("data", "Data loss"), ("wave", "Wave residual"),
             ("gauge", "Gauge div(psi)"), ("ic", "Initial condition"),
             ("bdry", "Boundary (Dirichlet)"), ("total", "Total loss")]
    if not any(hist.get("train_bdry", [])):
        comps = [c for c in comps if c[0] != "bdry"]

    for key, title in comps:
        fig, ax = plt.subplots(figsize=(9, 7))
        tr = np.maximum(hist[f"train_{key}"], 1e-30)
        ax.plot(range(1, len(tr) + 1), tr, color=AC["blue"], lw=3.0, label="Train")
        if f"val_{key}" in hist:
            va = np.maximum(hist[f"val_{key}"], 1e-30)
            ax.plot(range(1, len(va) + 1), va, color=AC["amber"], lw=3.0,
                    label="Validation")
        if 0 < data_only_epochs < len(tr):
            ax.axvline(data_only_epochs, color=AC["red"], lw=2.0, ls=":",
                       label="physics on")
        ax.set_yscale("log")
        ax.set_xlabel("Epoch", fontsize=30)
        ax.set_ylabel("MSE (standardized)", fontsize=30)
        ax.set_title(title, fontsize=34)
        ax.tick_params(axis="both", labelsize=24)
        ax.legend(frameon=False, fontsize=24)
        fig.tight_layout()
        stem = f"{save_stem}_{key}" if save_stem else None
        save_fig(fig, stem)


plot_loss_curves(history, DATA_ONLY_EPOCHS, save_stem="outputs/loss_curve")

"""## Reconstruction on seen points

Full-time `(u, v, w)` reconstruction at trained (seen) spatial points, where
the model was given only `SUBSAMPLE_KEEP` (10%) of each signal. Ground truth is
overlaid; the seen training timesteps are a small subset of the curve, so the
fit between them is interpolation in time.
"""

def reconstruct_xy(model, data, xy_index, z, device, n_t=N_T):
    sc = data["scalers"]
    beta_y, beta_z = sc.beta_y, sc.beta_z
    px, py = data["xy_points"][xy_index]
    t_full = np.arange(1, n_t + 1) * DT
    X = sc.encode(np.full(n_t, px), np.full(n_t, py), np.full(n_t, z), t_full)
    Xg = torch.tensor(X, dtype=next(model.parameters()).dtype,
                      device=device).requires_grad_(True)
    model.eval()
    # Network predicts standardized displacement; map back to physical mm.
    uvw_hat = displacement(model, Xg, beta_y, beta_z).detach().cpu().numpy()
    pred = sc.decode_fields(uvw_hat)

    frame = data["df"]
    mask = ((np.abs(frame["x"].to_numpy() - px) < 1e-6)
            & (np.abs(frame["y"].to_numpy() - py) < 1e-6)
            & (np.abs(frame["z"].to_numpy() - z) < 1e-6))
    grp = frame[mask].sort_values("t")
    gt = np.full((n_t, 3), np.nan)
    gt[grp["t_idx"].to_numpy()] = grp[FIELD_COLS].to_numpy()
    train_keep = np.zeros(n_t, bool)
    train_keep[grp["t_idx"].to_numpy()] = grp["is_train"].to_numpy()
    return {"pred": pred, "gt": gt, "point": (px, py, z),
            "train_idx": np.where(train_keep)[0],
            "test_idx": np.where(~train_keep)[0]}


def relative_l2(pred, target):
    d = np.linalg.norm(target)
    return float(np.linalg.norm(pred - target) / d) if d > 0 else float(np.linalg.norm(pred - target))

def plot_reconstruction(recs, save_stem=None,
                        title="Helmholtz-potential PINN reconstruction (u/v/w)"):
    n = len(recs); comps = ["u", "v", "w"]
    fig, axes = plt.subplots(n, 3, figsize=(22, 4.2 * n), squeeze=False)
    t = np.arange(len(recs[0]["pred"]))
    for i in range(n):
        px, py, _ = recs[i]["point"]
        for ci, comp in enumerate(comps):
            ax = axes[i][ci]
            gt = recs[i]["gt"][:, ci]
            ax.plot(t, gt, color=AC["ink"], lw=2.0, label="Ground truth")
            ax.plot(t, recs[i]["pred"][:, ci], color=AC["red"], lw=2.2, ls="--",
                    alpha=0.9, label="PINN")
            if ci == 0:
                ax.set_ylabel(f"x={px:.1f}\ny={py:.1f}")
            if i == 0:
                ax.set_title(f"component {comp}")
            if i == 0 and ci == 2:
                ax.legend(frameon=False, loc="upper right")
    for ci in range(3):
        axes[-1][ci].set_xlabel("Timestep index")
    fig.suptitle(title, y=1.005)
    fig.tight_layout()
    save_fig(fig, save_stem)

"""## Held-out spatial point prediction

Time-signal prediction at the spatially excluded points. These points were
removed from training entirely, so the model has seen no timestep of them at
all. The whole curve is a spatial extrapolation, not a fit.
"""

def select_heldout_points(data, k=5, seed=SEED):
    """Return up to k indices of spatially held-out points.

    These are the points excluded from training entirely in stage 1 of the
    split. If more than k exist, a seeded random subset spread across their
    neighborhoods is returned. Indices are into data["xy_points"].
    """
    held = list(data["held_spatial_idx"])
    if len(held) <= k:
        return sorted(held)
    nbhd = data["nbhd_of_point"]
    rng = np.random.RandomState(seed)
    # round-robin over neighborhoods so the chosen subset stays spread out
    by_group = {}
    for i in held:
        by_group.setdefault(nbhd[i], []).append(i)
    for g in by_group:
        rng.shuffle(by_group[g])
    order = sorted(by_group.keys(), key=lambda g: str(g))
    chosen, gi = [], 0
    while len(chosen) < k:
        g = order[gi % len(order)]
        if by_group[g]:
            chosen.append(by_group[g].pop())
        gi += 1
    return sorted(chosen)


def plot_heldout_prediction(recs, save_stem=None,
                            title="Held-out spatial point prediction (u/v/w)"):
    """Time-signal prediction at spatially held-out points.

    The model saw no timestep of these points, so the entire curve is a
    prediction.
    """
    n = len(recs); comps = ["u", "v", "w"]
    fig, axes = plt.subplots(n, 3, figsize=(22, 4.2 * n), squeeze=False)
    t = np.arange(len(recs[0]["pred"]))
    for i in range(n):
        px, py, _ = recs[i]["point"]
        for ci, comp in enumerate(comps):
            ax = axes[i][ci]
            gt = recs[i]["gt"][:, ci]
            ax.plot(t, gt, color=AC["ink"], lw=2.0, label="Ground truth")
            ax.plot(t, recs[i]["pred"][:, ci], color=AC["red"], lw=2.2, ls="--",
                    alpha=0.9, label="PINN (unseen point)")
            if ci == 0:
                ax.set_ylabel(f"x={px:.1f}\ny={py:.1f}")
            if i == 0:
                ax.set_title(f"component {comp}")
            if i == 0 and ci == 2:
                ax.legend(frameon=False, loc="upper right")
    for ci in range(3):
        axes[-1][ci].set_xlabel("Timestep index")
    fig.suptitle(title, y=1.005)
    fig.tight_layout()
    save_fig(fig, save_stem)


heldout_xy = select_heldout_points(data, k=5)
recs_heldout = [reconstruct_xy(model, data, i, SURFACE_Z, DEVICE)
                for i in heldout_xy]
plot_heldout_prediction(recs_heldout, save_stem="outputs/heldout_prediction")

def select_seen_points(data, k=5, seed=SEED):
    """Return up to k indices of trained (seen) points, spread across groups.

    A seen point has at least one kept training timestep and is not in the
    spatial holdout. Indices are into data["xy_points"].
    """
    df = data["df"]
    xy = data["xy_points"]
    held = set(data["held_spatial_idx"])
    key_to_idx = {(px, py): i for i, (px, py) in enumerate(map(tuple, xy))}
    trained_keys = (df[df["is_train"]][["x", "y"]]
                    .drop_duplicates().itertuples(index=False, name=None))
    seen = sorted({key_to_idx[k] for k in trained_keys
                   if k in key_to_idx and key_to_idx[k] not in held})
    if len(seen) <= k:
        return seen
    nbhd = data["nbhd_of_point"]
    rng = np.random.RandomState(seed)
    by_group = {}
    for i in seen:
        by_group.setdefault(nbhd[i], []).append(i)
    for g in by_group:
        rng.shuffle(by_group[g])
    order = sorted(by_group.keys(), key=lambda g: str(g))
    chosen, gi = [], 0
    while len(chosen) < k:
        g = order[gi % len(order)]
        if by_group[g]:
            chosen.append(by_group[g].pop())
        gi += 1
    return sorted(chosen)


seen_xy = select_seen_points(data, k=5)
recs = [reconstruct_xy(model, data, i, SURFACE_Z, DEVICE) for i in seen_xy]
plot_reconstruction(recs, save_stem="outputs/reconstruction")

"""### Held-out reconstruction error

Relative L2 over the held-out timesteps, per demo point.
"""

# Relative L2 on the temporally held-out timesteps of the seen reconstruction
# points (the timesteps the model did not train on, at points it did).
errs = []
used = []
for idx, rec in zip(seen_xy, recs):
    ti = rec["test_idx"]
    if len(ti) == 0:
        continue
    valid = ~np.isnan(rec["gt"][ti]).any(axis=1)
    if valid.sum() == 0:
        continue
    errs.append(relative_l2(rec["pred"][ti][valid], rec["gt"][ti][valid]))
    used.append(idx)
errs = np.array(errs)
if len(errs):
    print(f"relative L2 (seen points, unseen timesteps) | "
          f"median={np.median(errs):.3e} | mean={np.mean(errs):.3e}")
    for i, e in zip(used, errs):
        print(f"  point {i}: {e:.3e}")
else:
    print("no temporally held-out timesteps among the seen reconstruction points")

"""## Save checkpoint"""

os.makedirs("outputs", exist_ok=True)
torch.save({
    "state_dict": model.state_dict(),
    "history": history,
    "metrics": metrics,
    "scalers": vars(data["scalers"]),
}, "outputs/model.pt")
print("saved: outputs/model.pt")

"""## Hyperparameter sweep

Grid over architecture (width/depth, Fourier frequencies) and the main training knobs (learning rate, physics gradient fraction, boundary weight). Run on GPU; trim grids or `SWEEP_EPOCHS` for a quick scan, then refit the winner at full `EPOCHS`.
"""

# ---------------------------------------------------------------------------
# Hyperparameter sweep (run on GPU)
# ---------------------------------------------------------------------------
# Grid over architecture and the main training knobs. Each configuration
# temporarily overrides the relevant globals, rebuilds the network, trains, and
# records the best held-out validation data MSE plus the final physics terms.
# Results are sorted best-first and returned as a DataFrame.
#
# This is deliberately a cell you launch on your A100: a full grid is many
# minutes of GPU time per point. Trim the grids or set SWEEP_EPOCHS lower for a
# quick scan, then refit the winner at full EPOCHS.

import itertools

SWEEP_EPOCHS = 60          # shorter than EPOCHS for scanning; refit winner after
SWEEP_SEED = SEED

SWEEP_GRID = {
    "HIDDEN_SIZES": [[128, 128, 128], [256, 256, 256], [256, 256, 256, 256]],
    "NUM_FREQ": [96, 160, 256],
    "LR": [1e-3, 2e-3],
    "BALANCE_ALPHA": [0.1, 0.3, 0.5],
    "W_BDRY": [0.5, 1.0, 2.0],
}

# Globals the sweep is allowed to mutate. Saved and restored around the loop.
_SWEEP_KEYS = list(SWEEP_GRID.keys()) + ["EPOCHS"]


def _snapshot_globals(keys):
    return {k: globals()[k] for k in keys}


def _restore_globals(snap):
    for k, v in snap.items():
        globals()[k] = v


def run_sweep(data, device, grid=SWEEP_GRID, sweep_epochs=SWEEP_EPOCHS,
              seed=SWEEP_SEED, verbose=False):
    saved = _snapshot_globals(_SWEEP_KEYS)
    names = list(grid.keys())
    combos = list(itertools.product(*[grid[n] for n in names]))
    print(f"[sweep] {len(combos)} configurations x {sweep_epochs} epochs each")

    rows = []
    try:
        globals()["EPOCHS"] = sweep_epochs
        for ci, combo in enumerate(combos, 1):
            cfg = dict(zip(names, combo))
            for k, v in cfg.items():
                globals()[k] = v
            set_seed(seed)
            net = make_net(data["scalers"], seed).to(device)
            t0 = time.time()
            hist, metrics = train(net, data, device, verbose=verbose)
            elapsed = (time.time() - t0) / 60.0
            row = dict(cfg)
            row["HIDDEN_SIZES"] = "x".join(map(str, cfg["HIDDEN_SIZES"]))
            row["val_data_mse"] = metrics["val_data_mse"]
            row["final_wave"] = hist["val_wave"][-1]
            row["final_gauge"] = hist["val_gauge"][-1]
            row["final_ic"] = hist["val_ic"][-1]
            row["final_bdry"] = hist["val_bdry"][-1]
            row["minutes"] = elapsed
            rows.append(row)
            print(f"  [{ci:02d}/{len(combos)}] {row['HIDDEN_SIZES']:>18} "
                  f"F={cfg['NUM_FREQ']:>3} lr={cfg['LR']:.0e} "
                  f"a={cfg['BALANCE_ALPHA']:.1f} wB={cfg['W_BDRY']:.1f} "
                  f"-> val {row['val_data_mse']:.3e} ({elapsed:.1f}m)")
    finally:
        _restore_globals(saved)

    results = pd.DataFrame(rows).sort_values("val_data_mse").reset_index(drop=True)
    print("\n[sweep] best configuration:")
    print(results.iloc[0].to_string())
    return results


# Launch (uncomment on GPU):
# sweep_results = run_sweep(data, DEVICE)
# sweep_results.to_csv("outputs/sweep_results.csv", index=False)
# sweep_results.head(10)